// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk89ZrwMooHUwI2i7BGwEOdGTcEcnmBRM',
    appId: '1:1002734626968:web:c91b53b82f8c8bf28ec8ed',
    messagingSenderId: '1002734626968',
    projectId: 'tech-store-f142a',
    authDomain: 'tech-store-f142a.firebaseapp.com',
    storageBucket: 'tech-store-f142a.firebasestorage.app',
    measurementId: 'G-ZLSCZXY5VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9fYdEPSHrBKvYejfCmdVqfsFcoxeS-Qc',
    appId: '1:1002734626968:android:60f94b4c60ff04bb8ec8ed',
    messagingSenderId: '1002734626968',
    projectId: 'tech-store-f142a',
    storageBucket: 'tech-store-f142a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSF4TogNsEMp273LYsxxbXYzjKc5kVto0',
    appId: '1:1002734626968:ios:77cfda355c0579f88ec8ed',
    messagingSenderId: '1002734626968',
    projectId: 'tech-store-f142a',
    storageBucket: 'tech-store-f142a.firebasestorage.app',
    iosBundleId: 'com.example.projectPrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk89ZrwMooHUwI2i7BGwEOdGTcEcnmBRM',
    appId: '1:1002734626968:web:f4b5e3040cff19c68ec8ed',
    messagingSenderId: '1002734626968',
    projectId: 'tech-store-f142a',
    authDomain: 'tech-store-f142a.firebaseapp.com',
    storageBucket: 'tech-store-f142a.firebasestorage.app',
    measurementId: 'G-Z0PHP81G5B',
  );
}
